import type { Transaction, ScannedProduct, Achievement, GalleryItem } from "./types";

/** Today is 2026-06-21 (Sunday). Week = Mon 15 → Sun 21 Jun. */
export const initialTransactions: Transaction[] = [
  // ── this week (15-21 Jun) ──
  {
    id: "t1",
    type: "income",
    category: "Gaji",
    note: "Gaji bulan ini",
    amount: 8500000,
    date: "2026-06-20T09:00:00+07:00",
    icon: "salary",
  },
  {
    id: "t2",
    type: "expense",
    category: "Kopi",
    note: "Kopi pagi",
    amount: 28000,
    date: "2026-06-20T07:30:00+07:00",
    icon: "coffee",
  },
  {
    id: "t3",
    type: "expense",
    category: "Belanja",
    note: "Grocery mingguan",
    amount: 215000,
    date: "2026-06-19T18:20:00+07:00",
    icon: "cart",
  },
  {
    id: "t4",
    type: "expense",
    category: "Makan",
    note: "Makan siang",
    amount: 45000,
    date: "2026-06-19T12:40:00+07:00",
    icon: "food",
  },
  {
    id: "t5",
    type: "income",
    category: "Hadiah",
    note: "Uang ultah",
    amount: 500000,
    date: "2026-06-18T10:00:00+07:00",
    icon: "gift",
  },
  {
    id: "t6",
    type: "expense",
    category: "Transport",
    note: "Bensin",
    amount: 60000,
    date: "2026-06-18T08:15:00+07:00",
    icon: "transport",
  },
  {
    id: "t7",
    type: "expense",
    category: "Kopi",
    note: "Ngopi sore",
    amount: 32000,
    date: "2026-06-17T16:00:00+07:00",
    icon: "coffee",
  },
  {
    id: "t8",
    type: "expense",
    category: "Hiburan",
    note: "Bioskop",
    amount: 75000,
    date: "2026-06-16T20:10:00+07:00",
    icon: "entertainment",
  },
  {
    id: "t9",
    type: "expense",
    category: "Makan",
    note: "Sarapan",
    amount: 22000,
    date: "2026-06-15T08:00:00+07:00",
    icon: "food",
  },
  // ── last week (8-14 Jun) ──
  {
    id: "t10",
    type: "expense",
    category: "Belanja",
    note: "Laundry",
    amount: 35000,
    date: "2026-06-12T19:00:00+07:00",
    icon: "cart",
  },
  {
    id: "t11",
    type: "expense",
    category: "Transport",
    note: "Gojek",
    amount: 18000,
    date: "2026-06-10T09:30:00+07:00",
    icon: "transport",
  },
];

/** Mock barcode scan results — the scanner randomly returns one of these. */
export const productCatalog: ScannedProduct[] = [
  { name: "Kopi Susu Gula Aren", price: 25000, category: "Kopi", icon: "coffee" },
  { name: "Air Mineral 600ml", price: 5000, category: "Makan", icon: "food" },
  { name: "Roti Tawar Sisir", price: 18000, category: "Belanja", icon: "cart" },
  { name: "Tiket Bus", price: 12000, category: "Transport", icon: "transport" },
  { name: "Voucher Game", price: 50000, category: "Hiburan", icon: "entertainment" },
];

export const achievements: Achievement[] = [
  {
    id: "a1",
    title: "Pelajar Hemat",
    desc: "Catat 10 transaksi pertama",
    icon: "piggy",
    status: "unlocked",
    progress: 1,
  },
  {
    id: "a2",
    title: "Streak 7 Hari",
    desc: "Catat transaksi 7 hari beruntun",
    icon: "flame",
    status: "progress",
    progress: 0.71,
  },
  {
    id: "a3",
    title: "Penyimpan Setia",
    desc: "Saldo di atas Rp5 juta",
    icon: "trophy",
    status: "unlocked",
    progress: 1,
  },
  {
    id: "a4",
    title: "Target Bulanan",
    desc: "Pengeluaran di bawah budget",
    icon: "target",
    status: "progress",
    progress: 0.42,
  },
  {
    id: "a5",
    title: "Master Investasi",
    desc: "Sisihkan Rp1 juta",
    icon: "trending",
    status: "locked",
    progress: 0,
  },
  {
    id: "a6",
    title: "Rutinitas Kopi",
    desc: "5 transaksi kopi",
    icon: "coffee",
    status: "locked",
    progress: 0,
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "g1",
    title: "Gaji Juni",
    subtitle: "Pemasukan terbesar",
    amount: 8500000,
    type: "income",
    icon: "salary",
    gradient: "from-mint-500/30 to-forest-600/30",
  },
  {
    id: "g2",
    title: "Grocery",
    subtitle: "Belanja mingguan",
    amount: 215000,
    type: "expense",
    icon: "cart",
    gradient: "from-gold-500/30 to-rose-500/20",
  },
  {
    id: "g3",
    title: "Bioskop",
    subtitle: "Hiburan akhir pekan",
    amount: 75000,
    type: "expense",
    icon: "entertainment",
    gradient: "from-purple-500/25 to-forest-700/30",
  },
  {
    id: "g4",
    title: "Hadiah Ultah",
    subtitle: "Kejutan manis",
    amount: 500000,
    type: "income",
    icon: "gift",
    gradient: "from-mint-400/25 to-gold-400/20",
  },
  {
    id: "g5",
    title: "Kopi Streak",
    subtitle: "3x minggu ini",
    amount: 60000,
    type: "expense",
    icon: "coffee",
    gradient: "from-rose-500/25 to-gold-500/20",
  },
];
